version: '3.9'
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
#test1
