version: '3.8'

services:

  database:
    build: ./
    image: postgres:15
    container_name: database
    restart: on-failure
    volumes:
      - "./backend/data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    # environment:
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmimn
    restart: on-failure
    depends_on:
      - database
    ports:
      - 5050:80
    links:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@42.fr
      PGADMIN_DEFAULT_PASSWORD: admin

  backend:
    build: ./backend
    container_name: backend
    # environment:
    #   - 
    ports:
      - 7000:7000
    links:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    # environment:
    #   - 
    ports:
      - 3000:3000
    links:
      - backend


volumes:
  database:
    driver: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: ./backend/database