version: '3.9'
services:
  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "4000:4000"
      - "5500:5500"
    volumes:
    - /var/www/photos:/app/photos
    restart: on-failure
    
  frontend:
    container_name: frontend 
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
