name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH into VM and deploy
      run: |
        sshpass -p '${{ secrets.VM_PASS }}' ssh -o StrictHostKeyChecking=no '${{ secrets.USER }}'@'${{ secrets.VM_IP }}' 'cd ft_transendence && git pull && docker-compose up --build -d'
