name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH into VM and deploy
      run: |
        sshpass -p '${{ secrets.VM_PASS }}' ssh -o StrictHostKeyChecking=no gevorg@20.123.193.166 'cd ft_transendence && git pull && docker compose up --build -d'
        
    - name: Sleep for 15 seconds
      run: sleep 15
      
    - name: Is backend down?
      run: | 
         output=$(sshpass -p '${{ secrets.VM_PASS }}' ssh -o StrictHostKeyChecking=no gevorg@20.123.193.166 'docker ps | wc -l')
         if [ "$output" != "4" ]; then
           sshpass -p '${{ secrets.VM_PASS }}' ssh -o StrictHostKeyChecking=no gevorg@20.123.193.166 'docker logs ft_transendence-backend-1'
           exit 1
         fi
